# Generated by Django 5.0 on 2023-12-16 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oppertunities_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='intern')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organiser', models.CharField(max_length=100)),
                ('apply', models.URLField()),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('is_online', models.BooleanField(blank=True, default=False, null=True)),
                ('is_offline', models.BooleanField(blank=True, default=False, null=True)),
                ('openings', models.IntegerField()),
                ('skillsrequired', models.CharField(blank=True, max_length=100, null=True)),
                ('maxpay', models.IntegerField(blank=True, null=True)),
                ('minpay', models.IntegerField(blank=True, null=True)),
                ('is_scholarship', models.BooleanField(default=False)),
                ('is_hack', models.BooleanField(default=False)),
                ('is_intern', models.BooleanField(default=False)),
                ('onlinemode', models.BooleanField(default=False)),
                ('offlinemode', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
