# Generated by Django 5.0 on 2023-12-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hackathon',
            new_name='Hackathon_model',
        ),
        migrations.RenameModel(
            old_name='InternJob',
            new_name='InternJob_model',
        ),
        migrations.RenameModel(
            old_name='Scholarship',
            new_name='Scholarship_model',
        ),
    ]
