# Generated by Django 5.0 on 2023-12-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_hackathon_hackathon_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship_model',
            name='amount_given',
            field=models.IntegerField(),
        ),
    ]
