# Generated by Django 5.0 on 2023-12-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_oppertunities_model_delete_hackathon_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oppertunities_model',
            name='openings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
