# Generated by Django 5.0 on 2023-12-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('1', 'Aadhar Card'), ('2', 'Pan Card'), ('3', 'Voter Id'), ('4', 'Health Card'), ('5', 'ABC'), ('6', 'Driving Licience'), ('7', '10th Marksheet'), ('8', '12th Marksheet'), ('9', 'Migration'), ('10', 'Trancerfer Certificate'), ('11', 'Marksheet'), ('12', 'GAP Certificate'), ('13', 'Admission Slip'), ('14', 'Domacile'), ('15', 'Income'), ('16', 'Caste'), ('17', 'Samagra'), ('18', 'Bank Passbook')], max_length=100)),
                ('documnet_number', models.BigIntegerField()),
                ('document', models.FileField(upload_to='documents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
