# Generated by Django 5.0 on 2023-12-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadform',
            name='document_type',
            field=models.CharField(choices=[('Aadhar Card', 'Aadhar Card'), ('Pan Card', 'Pan Card'), ('Voter Id', 'Voter Id'), ('Health Card', 'Health Card'), ('ABC', 'ABC'), ('Driving Licience', 'Driving Licience'), ('10th Marksheet', '10th Marksheet'), ('12th Marksheet', '12th Marksheet'), ('Migration', 'Migration'), ('Trancerfer Certificate', 'Trancerfer Certificate'), ('Marksheet', 'Marksheet'), ('GAP Certificate', 'GAP Certificate'), ('Admission Slip', 'Admission Slip'), ('Domacile', 'Domacile'), ('Income', 'Income'), ('Caste', 'Caste'), ('Samagra', 'Samagra'), ('Bank Passbook', 'Bank Passbook')], max_length=100),
        ),
    ]
