# Generated by Django 5.0 on 2023-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_uploadform_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orga_name', models.CharField(max_length=255, unique=True)),
                ('da_to', models.DateField()),
                ('da_from', models.DateField()),
                ('max_members', models.IntegerField()),
                ('link_to', models.URLField()),
                ('on_mode', models.BooleanField(default=False)),
                ('off_mode', models.BooleanField(default=False)),
                ('short_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InternJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, unique=True)),
                ('du_to', models.DateField()),
                ('du_from', models.DateField()),
                ('skill_req', models.CharField(max_length=255)),
                ('no_openning', models.IntegerField()),
                ('max_pay', models.IntegerField()),
                ('min_pay', models.IntegerField()),
                ('short_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orga_name', models.CharField(max_length=255, unique=True)),
                ('da_to', models.DateField()),
                ('da_from', models.DateField()),
                ('min_percent', models.IntegerField()),
                ('amount_given', models.ImageField(upload_to='')),
                ('on_mode', models.BooleanField(default=False)),
                ('off_mode', models.BooleanField(default=False)),
                ('short_desc', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='uploadform',
            old_name='documnet_number',
            new_name='document_number',
        ),
    ]
