# Generated by Django 5.0 on 2023-12-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_hackathon_internjob_scholarship_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hackathon',
        ),
        migrations.DeleteModel(
            name='InternJob',
        ),
        migrations.DeleteModel(
            name='Scholarship',
        ),
    ]
