# Generated by Django 5.0 on 2023-12-15 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_delete_hackathon_delete_internjob_delete_scholarship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadform',
            unique_together={('document_type', 'user')},
        ),
    ]
